[package]
name = "builder"
version = "0.1.0"
edition = "2021"
authors = ["Dawid Janeczko"]

[lib]
proc-macro = true

[dependencies]
paste = "1.0.12"
proc-macro2 = "1.0.56"
quote = "1.0.26"
syn = { version = "2.0.15", features = ["extra-traits", "full"] }
toml = "0.7.3"
