[package]
name = "easydev"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "crates/builder"
]

[workspace.package]
name = "easydev"
version = "0.1.0"
edition = "2021"

[features]
builder = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
builder = { path = "crates/builder" }
